### ISSUE TITLE
Wrong path in racon Dockerfile

### ISSUE THREAD

**Issue by ghost** [ttubb/autopore#2]
Hey,

I wanted to use the racon docker image and found that the path to the binary is wrong. It should be /software/racon/build/bin instead of /software/racon/bild/bin.

**Comment by ttubb** [comment]
Thank you! That version should not have been pushed to the repo. It's fixed now, sorry for my long hiatus.

Racon has proven problematic in that it will not run in AMD CPUs if compiled on an Intel-based system. Since the images are being build on Dockerhub, the outcome is a lottery at the moment.
